version: '3.8'

services:
  web:
    build:
      context: .
      args:
        BUILD_ENVIRONMENT: ${BUILD_ENVIRONMENT}
    command: >
      sh -c "if [ \"$BUILD_ENVIRONMENT\" = \"development\" ]; then
             daphne -b 0.0.0.0 -p 8012 config.asgi:application;
             else
             gunicorn config.asgi:application -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8012;
             fi"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8012:8012"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - app-network
    restart: unless-stopped
    entrypoint: /app/docker-entrypoint.sh

  celery:
    build:
      context: .
      args:
        BUILD_ENVIRONMENT: ${BUILD_ENVIRONMENT}
    command: celery -A config worker -l INFO
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env
    depends_on:
      - redis
      - db
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:7
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume:
